version: "3.8"
services:
  api:
    build: .
    container_name: csc-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres-db
      - minio
    restart: unless-stopped

  postgres-db:
    image: postgres:15-alpine
    container_name: csc-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=csc_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: csc-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  pgdata:
  miniodata: